name: Secret Scan

on:
  pull_request:
    branches: [main, stabilize/**]
  push:
    branches: [main]

jobs:
  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Report Results
        if: failure()
        run: |
          echo "::error::Secrets detected! Please remove them before merging."
          exit 1
